app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::resource('site', 'SiteController');

Route::get('/', function () {
    return view('pages.sites');
});

app/Site.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Site extends Model
{
    // setup mass assignment
    protected $fillable = [
            'url',
            'sitemap',
            'analytics',
            'responsetime',
            'pagesup'
        ];
        
    public function logs()
    {
        return $this->hasMany(\App\SiteLog::class);
    }
    
    public function getAvgResponseTime()
    {
        return (int)$this->logs()->crawled()->latest()->withSuccess()->take(100)->avg('responsetime');
    }
    
    public function getPagesUp()
    {
        return (int)$this->logs()->crawled()->withSuccess()->count();
    }
    
    public function getPagesDown()
    {
        return (int)$this->logs()->crawled()->withError()->count();
    }
}

app/SiteLog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SiteLog extends Model
{
    protected $fillable = [
            'site_id',
            'url',
            'responseCode',
            'responseTime',
            'crawled'
        ];
        
    public function site()
    {
        return $this->belongsTo(\App\Site::class);
    }
    
    public function scopeCrawled($query, $status = true)
    {
        return $query->where('crawled', $status);
    }
    
    public function scopeWithCode($query, $code = 200)
    {
        return $query->where('responseCode', $code);
    }
    
    public function scopeWithSuccess($query)
    {
        return $query->whereIn('responseCode', [200,301,302]);
    }
    
    public function scopeWithError($query)
    {
        return $query->whereNotIn('responseCode', [200,301,302]);
    }
    
    public function scopeLatest($query)
    {
        return $query->orderBy('created_at','desc');
    }
    
    public function scopeOldest($query)
    {
        return $query->orderBy('created_at','asc');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Event;
use App\Events\ReadyForPing;

class SiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.sites');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the form
        $this->validate($request, [
            'url' => 'required|url|unique:sites|max:255'
        ]);
        
        // add a new site if it doesn't already exist
        $site = \App\Site::create($request->all());
        // add homepage to be crawled
        $site->logs()->create($request->all());
        return redirect()->back()->with('success','Site created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $site = \App\Site::find($id);
        return view('pages.logs')->with('site',$site);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Site::find($id)->delete();
        return redirect()->back()->with('success', 'Site deleted');
    }
}

resources/views/elements/navigation.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SEO Checker</a>
    </div>
    <!--<div id="navbar" class="collapse navbar-collapse">-->
    <!--  <ul class="nav navbar-nav">-->
    <!--    <li><a href="{{ route('site.index') }}">Sites</a></li>-->
    <!--  </ul>-->
    <!--</div>-->
    <!--/.nav-collapse -->
  </div>
</nav>

resources/views/master/bootstrap.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    @section('head')
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@yield('head-title', 'SEO Checker')</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <style>
        body { padding-top: 50px; }
        .padding { padding: 40px 15px; }
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @show
</head>

<body>
    
    @include('elements.navigation')
        <div class="container padding">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if (session('info'))
                <div class="alert alert-info">
                    {{ session('info') }}
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @section('body')
            <div class="row">
                <div class="col-lg-6">
                    <h4>Subheading</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
        
                    <h4>Subheading</h4>
                    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
        
                    <h4>Subheading</h4>
                    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
                </div>
        
                <div class="col-lg-6">
                    <h4>Subheading</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
        
                    <h4>Subheading</h4>
                    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
        
                    <h4>Subheading</h4>
                    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
                </div>
            </div>
            @show
            <footer class="footer">
                <p>&copy; 2015 Marco Mark</p>
            </footer>
        </div>
    <!-- /container -->

    @section('scripts')
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    @show
</body>

</html>

resources/views/pages/logs.blade.php
@extends('master.bootstrap')

@section('body')
    <div class="row">
        <div class="col-md-12">
            <h4>Logs</h4>
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>URL</th>
                        <th>Status</th>
                        <th>Ping</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($site->logs->take(100) as $log)
                    <tr>
                        <td>{{ $log->created_at }}</td>
                        <td>{{ $log->url }}</td>
                        <td>{{ $log->responseCode }}</td>
                        <td>{{ $log->responseTime }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/pages/sites.blade.php
@extends('master.bootstrap')

@section('body')
    <div class="row">
        <div class="col-md-12">
            <h4>Sites</h4>
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>Site</th>
                        <th>Sitemap</th>
                        <th>Analytics</th>
                        <th>Pages</th>
                        <th class="hidden-xs">Avg response time (ms)</th>
                        <th class="text-right hidden-xs">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (\App\Site::all() as $site)
                    <tr>
                        <td>{{ $site->url }}</td>
                        <td><span class="glyphicon {{ $site->sitemap ? 'glyphicon-ok text-success' : 'glyphicon-remove text-danger' }}" aria-hidden="true"></span></td>
                        <td><span class="glyphicon {{ $site->analytics ? 'glyphicon-ok text-success' : 'glyphicon-remove text-danger' }}" aria-hidden="true"></span></td>
                        <td><span class="label label-success">{{ $site->getPagesUp() }}</span> <span class="label label-danger">{{ $site->getPagesDown() }}</span></td>
                        <td class="hidden-xs">
                            <div class="progress">
                              <div class="progress-bar" role="progressbar" aria-valuenow="{{ $site->getAvgResponseTime() }}" aria-valuemin="0" aria-valuemax="1000" style="min-width: 2em; width: {{ $site->getAvgResponseTime() / 1000 * 100 }}%;">{{ $site->getAvgResponseTime() }}</div>
                            </div>
                        </td>
                        <td class="text-right hidden-xs">
                            <div class="btn-group" role="group" aria-label="...">
                                <a class="btn btn-primary btn-sm" href="{{ route('site.show',['id'=>$site->id]) }}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                                <button class="btn btn-danger btn-sm" data-href="{{ route('site.destroy',['id'=>$site->id]) }}" data-toggle="modal" data-target="#confirm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <p>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
                  Add site
                </button>
            </p>
        </div>
    </div>
    
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <form action="{{ route('site.store') }}" method="post">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Add a site</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="control-label sr-only" for="url">Website URL</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span></span>
                                <input type="text" class="form-control" name="url" id="url" placeholder="http://www.dewsign.co.uk">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                        {{ csrf_field() }}
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </form>
    </div>
    <!-- /.modal -->
    
    <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Delete site?
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this site and all associated logs?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok" data-method="DELETE">Delete</a>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    
    <script>
        window.csrfToken = '{{ csrf_token() }}';
        
        (function() {
            var laravel = {
                initialize: function() {
                    this.registerEvents();
                },
        
                registerEvents: function() {
                    $('body').on('click', 'a[data-method]', this.handleMethod);
                },
        
                handleMethod: function(e) {
                    var link = $(this);
                    var httpMethod = link.data('method').toUpperCase();
                    var form;
        
                    // If the data-method attribute is not PUT or DELETE,
                    // then we don't know what to do. Just ignore.
                    if ( $.inArray(httpMethod, ['PUT', 'DELETE']) === - 1 ) {
                        return;
                    }
        
                    // Allow user to optionally provide data-confirm="Are you sure?"
                    if ( link.data('confirm') ) {
                        if ( ! laravel.verifyConfirm(link) ) {
                            return false;
                        }
                    }
        
                    form = laravel.createForm(link);
                    form.submit();
        
                    e.preventDefault();
                },
        
                verifyConfirm: function(link) {
                    return confirm(link.data('confirm'));
                },
        
                createForm: function(link) {
                    var form =
                        $('<form>', {
                            'method': 'POST',
                            'action': link.attr('href')
                        });
        
                    var token =
                        $('<input>', {
                            'name': '_token',
                            'type': 'hidden',
                            'value': window.csrfToken
                        });
        
                    var hiddenInput =
                        $('<input>', {
                            'name': '_method',
                            'type': 'hidden',
                            'value': link.data('method')
                        });
        
                    return form.append(token, hiddenInput)
                        .appendTo('body');
                }
            };
        
            laravel.initialize();
        
        })();
        
        $( document ).ready(function() {
            $('#confirm').on('show.bs.modal', function(e) {
                $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
            });
        });
    </script>
@endsection